name: Rust

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Run lint
      run: cargo clippy --verbose
    - name: Build
      run: cargo build --verbose
    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: phantun-linux-x86_64
        path: |
          target/debug/client
          target/debug/server
        retention-days: 7
